import { StyleSheet } from 'react-native';
export const AssignByLevelScreenStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#EEF0F8',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 120,
  },
  searchBar: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchInput: {
    flex: 1,
    height: 48,
    paddingVertical: 0,
    fontSize: 14,
    color: '#1E293B',
  },
  typeFilterRow: {
    flexDirection: 'row',
    marginBottom: 18,
    padding: 4,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    gap: 4,
  },
  typeFilterButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  typeFilterButtonActive: {
    backgroundColor: '#FFFFFF',
  },
  typeFilterText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '900',
  },
  typeFilterTextActive: {
    color: '#1D4ED8',
  },
  levelSection: {
    marginBottom: 18,
  },
  sectionTitle: {
    color: '#1A202C',
    fontSize: 15,
    fontWeight: '900',
  },
  sectionMeta: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  multiSelectButton: {
    marginTop: 10,
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
  },
  multiSelectIconBox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  multiSelectCopy: {
    flex: 1,
    minWidth: 0,
  },
  multiSelectValue: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '900',
  },
  multiSelectPlaceholder: {
    color: '#94A3B8',
  },
  multiSelectHint: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  selectAllButton: {
    minHeight: 36,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  selectAllText: {
    color: '#4F46E5',
    fontSize: 12,
    fontWeight: '900',
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  questionRowSelected: {
    borderColor: '#4F46E5',
    backgroundColor: '#F5F3FF',
  },
  countPill: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  countPillSelected: {
    backgroundColor: '#4F46E5',
  },
  countText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '900',
  },
  countTextSelected: {
    color: '#FFFFFF',
  },
  questionContent: {
    flex: 1,
    minWidth: 0,
  },
  questionTitle: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 4,
  },
  questionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  questionMetaText: {
    color: '#4F46E5',
    fontSize: 11,
    fontWeight: '800',
  },
  checkbox: {
    marginLeft: 10,
  },
  checkboxUnchecked: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#CBD5E1',
  },
  checkboxChecked: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#4F46E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    alignItems: 'center',
    paddingTop: 44,
    gap: 8,
  },
  emptyText: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '700',
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 10,
  },
  footerCopy: {
    flex: 1,
  },
  footerLabel: {
    color: '#94A3B8',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  footerText: {
    color: '#1A202C',
    fontSize: 15,
    fontWeight: '900',
    marginTop: 2,
  },
  assignButton: {
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: '#1E3A8A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 18,
  },
  assignButtonBusy: {
    backgroundColor: '#64748B',
  },
  assignButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  levelModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.44)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  levelModal: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 10,
  },
  levelModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  levelModalTitle: {
    color: '#1A202C',
    fontSize: 17,
    fontWeight: '900',
  },
  levelModalSubtitle: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelOptionGrid: {
    gap: 8,
  },
  levelOption: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  levelOptionSelected: {
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
  },
  levelOptionText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '900',
  },
  levelOptionTextSelected: {
    color: '#4F46E5',
  },
  levelOptionEmpty: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  levelModalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
  },
  levelClearButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelClearText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '900',
  },
  levelDoneButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: '#4F46E5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelDoneText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  resultModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.48)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  resultModal: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '84%',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 10,
  },
  resultModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  resultTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  resultIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  resultModalTitle: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '900',
  },
  resultModalSubtitle: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  resultStats: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  resultStat: {
    flex: 1,
    minHeight: 66,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  resultStatValue: {
    color: '#1E293B',
    fontSize: 20,
    fontWeight: '900',
  },
  resultStatLabel: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 2,
    textAlign: 'center',
  },
  resultCountSummary: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 14,
  },
  resultScroll: {
    maxHeight: 390,
  },
  resultScrollContent: {
    paddingBottom: 4,
    gap: 14,
  },
  resultSection: {
    gap: 8,
  },
  resultSectionTitle: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '900',
  },
  resultStudentRow: {
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
  },
  resultStudentTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 6,
  },
  resultStudentName: {
    flex: 1,
    minWidth: 0,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '900',
  },
  resultStudentLevel: {
    color: '#4F46E5',
    fontSize: 11,
    fontWeight: '900',
  },
  resultQuestionText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  resultEmptyText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    paddingVertical: 4,
  },
  resultDoneButton: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: '#4F46E5',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  resultDoneText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});
