import { StyleSheet } from 'react-native';
export const CreateNewTaskScreenStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#EEF0F8',
  },
  keyboardAvoiding: {
    flex: 1,
  },
  contentScroll: {
    flex: 1,
  },
  contentScrollInner: {
    paddingBottom: 8,
  },

  // Title bar
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 10,
  },
  backBtn: { padding: 4 },
  pageTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1E3A5F',
    letterSpacing: -0.4,
  },

  // Card
  card: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 10,
    elevation: 3,
    overflow: 'hidden',
  },

  // Task ID
  taskIdSection: {
    backgroundColor: '#F0F4FA',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    marginBottom: 20,
  },
  taskIdLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.9,
    marginBottom: 4,
  },
  taskIdInput: {
    fontSize: 16,
    color: '#1E3A5F',
    fontWeight: '500',
    padding: 0,
  },
  levelOralRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    marginBottom: 20,
  },
  levelSection: {
    flex: 1,
    marginBottom: 0,
    paddingTop: 10,
    paddingBottom: 10,
  },
  levelDropdown: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  levelDropdownText: {
    fontSize: 16,
    color: '#1E3A5F',
    fontWeight: '700',
  },
  taskTypeRow: {
    flexDirection: 'row',
    marginBottom: 20,
    padding: 4,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    gap: 4,
  },
  taskTypeOption: {
    flex: 1,
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 8,
  },
  taskTypeOptionActive: {
    backgroundColor: '#FFFFFF',
  },
  taskTypeText: {
    flexShrink: 1,
    color: '#64748B',
    fontSize: 13,
    fontWeight: '800',
  },
  taskTypeTextActive: {
    color: '#1D4ED8',
  },
  oralOption: {
    flex: 1,
    backgroundColor: '#F0F4FA',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
  },
  oralOptionBody: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  oralOptionText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '800',
  },
  oralOptionTextActive: {
    color: '#1D4ED8',
  },
  levelModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.44)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  levelModal: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 10,
  },
  levelModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  levelModalTitle: {
    color: '#1A202C',
    fontSize: 17,
    fontWeight: '900',
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  levelOption: {
    width: 48,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelOptionActive: {
    backgroundColor: '#4F46E5',
    borderColor: '#4F46E5',
  },
  levelOptionText: {
    color: '#334155',
    fontSize: 15,
    fontWeight: '900',
  },
  levelOptionTextActive: {
    color: '#FFFFFF',
  },

  // Question list
  questionList: {
    marginBottom: 8,
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  expressionInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1E3A5F',
    padding: 0,
  },
  expressionPlaceholder: {
    fontWeight: '400',
  },
  answerText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#3B82F6',
    minWidth: 36,
    textAlign: 'right',
    marginLeft: 8,
  },
  errorText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#EF4444',
    minWidth: 36,
    textAlign: 'right',
    marginLeft: 8,
  },
  marksInput: {
    width: 54,
    height: 34,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    color: '#1E3A5F',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    padding: 0,
    marginLeft: 8,
  },
  dotsText: {
    fontSize: 16,
    color: '#CBD5E0',
    marginLeft: 8,
    letterSpacing: 2,
  },
  deleteBtn: {
    marginLeft: 10,
    padding: 2,
  },

  // Add question
  addQuestionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    borderRadius: 30,
    paddingVertical: 11,
    marginTop: 12,
    gap: 6,
  },
  addQuestionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  generateQuestionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563EB',
    borderRadius: 30,
    paddingVertical: 12,
    marginTop: 10,
    gap: 6,
  },
  generateQuestionText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  // Generator modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E3A5F',
  },
  generatorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  generatorField: {
    width: '47%',
    backgroundColor: '#F0F4FA',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
  },
  generatorLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  generatorInput: {
    fontSize: 18,
    color: '#1E3A5F',
    fontWeight: '700',
    padding: 0,
  },
  symbolRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 18,
  },
  symbolButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  symbolButtonActive: {
    borderColor: '#2563EB',
    backgroundColor: '#DBEAFE',
  },
  symbolButtonText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#64748B',
  },
  symbolButtonTextActive: {
    color: '#2563EB',
  },
  generateSubmitBtn: {
    backgroundColor: '#1E3A8A',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 13,
  },
  generateSubmitText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },

  // Blobs
  blobsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    paddingLeft: 8,
  },
  blob: {
    borderRadius: 100,
    opacity: 0.85,
  },

  // Footer / Save
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E3A8A',
    borderRadius: 30,
    paddingVertical: 16,
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  saveBtnDisabled: {
    backgroundColor: '#A0AEC0',
    shadowOpacity: 0,
    elevation: 0,
  },
  saveBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  saveIcon: {
    marginRight: 8,
  },
});
