import { StyleSheet } from 'react-native';
import { COLORS } from '../theme';
export const GameScreenStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#5BA8D4',
  },
  skyContainer: {
    flex: 1,
    backgroundColor: '#7EC8E8',
    overflow: 'hidden',
    position: 'relative',
  },
  skyGradientTop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#3D7EB8',
    opacity: 0.38,
    height: '55%',
  },
  skyGradientBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '35%',
    backgroundColor: '#C5EEFF',
    opacity: 0.45,
  },
  cloud: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  cloudPuff: {
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderRadius: 999,
  },
  cloudPuffMain: {
    width: 44,
    height: 28,
  },
  cloudPuffLeft: {
    width: 28,
    height: 22,
    marginBottom: 2,
    marginLeft: -10,
  },
  cloudPuffRight: {
    width: 32,
    height: 24,
    marginBottom: 4,
    marginLeft: -8,
  },
  cloudOne: {
    top: '12%',
    left: '8%',
    opacity: 0.92,
  },
  cloudTwo: {
    top: '22%',
    right: '10%',
    opacity: 0.85,
    transform: [{ scale: 1.15 }],
  },
  cloudThree: {
    top: '38%',
    left: '18%',
    opacity: 0.7,
    transform: [{ scale: 0.85 }],
  },
  sunGlow: {
    position: 'absolute',
    top: 8,
    right: 12,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#FFE566',
    opacity: 0.35,
  },
  sun: {
    position: 'absolute',
    top: 16,
    right: 20,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFD93D',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.5)',
    shadowColor: '#FFB800',
    shadowOpacity: 0.6,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 12,
    elevation: 4,
  },
  hillBack: {
    position: 'absolute',
    bottom: -20,
    left: -40,
    width: '75%',
    height: 90,
    borderTopLeftRadius: 80,
    borderTopRightRadius: 120,
    backgroundColor: '#5CB868',
    opacity: 0.55,
  },
  hillFront: {
    position: 'absolute',
    bottom: -28,
    right: -30,
    width: '70%',
    height: 80,
    borderTopLeftRadius: 100,
    borderTopRightRadius: 60,
    backgroundColor: '#6FD07A',
    opacity: 0.7,
  },
  readyOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(45, 100, 150, 0.55)',
  },
  readyContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  welcomeCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 28,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.8)',
    shadowColor: '#1A4A6E',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 8,
  },
  welcomeEmoji: {
    fontSize: 40,
    marginBottom: 4,
  },
  gameTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#2D4A6E',
    textAlign: 'center',
  },
  gameTitleAccent: {
    fontSize: 20,
    fontWeight: '800',
    color: '#4A90D9',
    textAlign: 'center',
    marginBottom: 8,
  },
  gameSubtitle: {
    fontSize: 14,
    color: '#5A6B7D',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  levelHeading: {
    alignSelf: 'flex-start',
    fontSize: 13,
    fontWeight: '800',
    color: '#2D4A6E',
    letterSpacing: 0.5,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  levelDropdownButton: {
    width: '100%',
    marginBottom: 20,
    borderRadius: 16,
    backgroundColor: '#F4F8FC',
    borderWidth: 2,
    borderColor: '#E2EAF2',
    overflow: 'hidden',
  },
  levelDropdownContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  levelDropdownEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  levelDropdownTextWrap: {
    flex: 1,
  },
  levelDropdownTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#2D4A6E',
  },
  levelDropdownSubtitle: {
    fontSize: 12,
    color: '#6B7C8F',
    marginTop: 2,
    fontWeight: '600',
  },
  levelDropdownArrow: {
    fontSize: 12,
    color: '#6B7C8F',
    fontWeight: '600',
  },
  levelModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  levelModalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
    paddingTop: 0,
  },
  levelModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2EAF2',
  },
  levelModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2D4A6E',
  },
  levelModalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F4F8FC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelModalCloseText: {
    fontSize: 18,
    color: '#6B7C8F',
    fontWeight: '600',
  },
  levelModalList: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  levelModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: '#F9FBFD',
  },
  levelModalItemSelected: {
    backgroundColor: '#E8F4FD',
    borderWidth: 2,
    borderColor: '#4A90D9',
  },
  levelModalItemEmoji: {
    fontSize: 22,
    marginRight: 12,
  },
  levelModalItemText: {
    flex: 1,
  },
  levelModalItemTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#2D4A6E',
  },
  levelModalItemDesc: {
    fontSize: 12,
    color: '#6B7C8F',
    marginTop: 2,
    fontWeight: '600',
  },
  levelModalItemCheck: {
    fontSize: 18,
    color: '#4A90D9',
    fontWeight: '800',
  },
  levelGrid: {
    width: '100%',
    marginBottom: 20,
  },
  levelChip: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: '#F4F8FC',
    borderWidth: 2,
    borderColor: '#E2EAF2',
    marginBottom: 8,
  },
  levelChipSelected: {
    backgroundColor: '#E8F4FD',
    borderColor: '#4A90D9',
  },
  levelEmoji: {
    fontSize: 22,
    marginRight: 12,
  },
  levelTextWrap: {
    flex: 1,
  },
  levelTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#2D4A6E',
  },
  levelTitleSelected: {
    color: '#2563A8',
  },
  levelDescription: {
    fontSize: 12,
    color: '#6B7C8F',
    marginTop: 1,
    fontWeight: '600',
  },
  levelDescriptionSelected: {
    color: '#4A7DB8',
  },
  levelCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#4A90D9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelCheckText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  startButton: {
    width: '100%',
    borderRadius: 22,
    backgroundColor: '#3DDC84',
    shadowColor: '#2BA86A',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.45)',
    overflow: 'hidden',
  },
  startButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 18,
  },
  startIconCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  startIcon: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 3,
  },
  startTextWrap: {
    flex: 1,
  },
  startButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  startButtonHint: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  controlsPanel: {
    backgroundColor: 'rgba(255, 246, 229, 0.97)',
    paddingTop: 8,
    borderTopWidth: 3,
    borderTopColor: COLORS.rod,
  },
});
