import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
export const ProgressDashboardStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#4F46E5',
  },
  container: {
    flex: 1,
    backgroundColor: '#F0F4FF',
  },
  header: {
    backgroundColor: '#4F46E5',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 24,
    paddingBottom: 32,
    paddingHorizontal: 24,
    marginBottom: 20,
    overflow: 'hidden',
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
  },
  waveContainer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  waveBg: {
    position: 'absolute',
    width: width * 2.5,
    height: 200,
    bottom: -80,
    left: -20,
    borderRadius: 120,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  headerEmoji: {
    fontSize: 48,
    marginRight: 6,
  },
  headerTitle: {
    flexShrink: 1,
    fontSize: 26,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    lineHeight: 32,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#C7D2FE',
    marginTop: 6,
    fontWeight: '600',
  },
  floatingStar: {
    fontSize: 22,
    opacity: 0.85,
  },
  floatingStarTop: {
    position: 'absolute',
    top: 30,
    right: 28,
  },
  floatingStarMiddle: {
    position: 'absolute',
    top: 90,
    right: 70,
  },
  floatingStarLeft: {
    position: 'absolute',
    top: 60,
    left: 20,
  },
  bottomSpacer: {
    height: 32,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  loaderWrap: {
    marginHorizontal: 16,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    gap: 8,
  },
  cardEmoji: { fontSize: 22 },
  cardTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1E1B4B',
    letterSpacing: 0.3,
  },
  circleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
    paddingVertical: 4,
  },
  statCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  statCircleValue: {
    fontSize: 20,
    fontWeight: '900',
  },
  statCircleLabel: {
    fontSize: 8,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 1,
  },
  statsTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 14,
  },
  statsRight: { alignItems: 'flex-end' },
  statsSmallLabel: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  accuracyValue: {
    fontSize: 40,
    fontWeight: '900',
    color: '#4F46E5',
    letterSpacing: -1,
  },
  totalSolvedValue: {
    fontSize: 28,
    fontWeight: '900',
    color: '#1E1B4B',
  },
  barTrack: {
    height: 18,
    backgroundColor: '#EEF2FF',
    borderRadius: 9,
    overflow: 'hidden',
    marginBottom: 20,
    position: 'relative',
  },
  barFill: {
    height: '100%',
    borderRadius: 9,
    backgroundColor: '#4F46E5',
    overflow: 'hidden',
  },
  barShine: {
    position: 'absolute',
    top: 3,
    left: 8,
    right: 8,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  barDot: {
    position: 'absolute',
    top: 6,
    width: 4,
    height: 6,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  pulseBadge: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 2,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  pulseBadgeIcon: { fontSize: 20 },
  pulseBadgeValue: {
    fontSize: 20,
    fontWeight: '900',
  },
  pulseBadgeLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  timeCard: {
    backgroundColor: '#1E1B4B',
    gap: 16,
  },
  practiceTimeCard: {
    backgroundColor: '#312E81',
    gap: 16,
  },
  timeCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  timeIcon: { fontSize: 40 },
  timeInfo: { flex: 1 },
  timeLabel: {
    fontSize: 11,
    color: '#818CF8',
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  practiceTimeLabel: {
    fontSize: 11,
    color: '#A5F3FC',
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  timeValue: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 2,
  },
  viewLogBtn: {
    backgroundColor: '#4F46E5',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  practiceLogBtn: {
    backgroundColor: '#0891B2',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.42,
    shadowRadius: 8,
    elevation: 6,
  },
  viewLogText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  cheerCard: {
    backgroundColor: '#FFF7ED',
    alignItems: 'center',
    paddingVertical: 24,
    borderWidth: 2,
    borderColor: '#FED7AA',
  },
  cheerEmoji: { fontSize: 44, marginBottom: 8 },
  cheerText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#92400E',
    letterSpacing: 0.3,
  },
  cheerSub: {
    fontSize: 13,
    color: '#B45309',
    fontWeight: '600',
    marginTop: 4,
  },
  versionText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 10,
  },
});
