import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
export const TopExplorerScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#EEF4FF',
  },
  adminHeaderWrap: {
    zIndex: 20,
    elevation: 20,
  },
  hidden: {
    display: 'none',
  },
  loaderWrap: {
    marginTop: 32,
  },
  emptyState: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 24,
    alignItems: 'center',
    marginTop: 28,
    shadowColor: '#A0B4D6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
  },
  emptyTitle: {
    fontSize: 18,
    color: '#1A3558',
    fontWeight: '900',
  },
  emptyText: {
    fontSize: 13,
    color: '#7A90B0',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
  },
  bgBlob: {
    position: 'absolute',
    width: width * 1.2,
    height: width * 1.2,
    borderRadius: width * 0.6,
    backgroundColor: '#D6E8FF',
    top: -width * 0.5,
    left: -width * 0.1,
    opacity: 0.6,
  },
  bgBlob2: {
    position: 'absolute',
    width: width * 0.8,
    height: width * 0.8,
    borderRadius: width * 0.4,
    backgroundColor: '#C8F0FF',
    top: 180,
    right: -width * 0.3,
    opacity: 0.35,
  },
  scrollContent: {
    paddingTop: 0,
    paddingHorizontal: 16,
  },

  // Header
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  headerSub: {
    fontSize: 13,
    color: '#7A90B0',
    fontWeight: '600',
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: '#1A3558',
    letterSpacing: 0.3,
  },
  filterBtn: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    shadowColor: '#A0B4D6',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  filterBtnActive: {
    backgroundColor: '#EAF1FB',
  },
  filterBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4A90D9',
  },
  filterBtnTextActive: {
    color: '#315A8C',
  },
  bottomSpacer: {
    height: 40,
  },
  levelModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.44)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  levelModal: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 10,
  },
  levelModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  levelModalTitle: {
    color: '#1A3558',
    fontSize: 17,
    fontWeight: '900',
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    color: '#334155',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
  },
  levelGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  levelAllOption: {
    height: 44,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  levelOption: {
    width: 48,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelOptionActive: {
    backgroundColor: '#4A90D9',
    borderColor: '#4A90D9',
  },
  levelOptionText: {
    color: '#334155',
    fontSize: 15,
    fontWeight: '900',
  },
  levelOptionTextActive: {
    color: '#FFFFFF',
  },

  // Podium
  podium: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginBottom: 14,
    position: 'relative',
    height: 250,
  },
  firstCard: {
    width: width * 0.38,
    backgroundColor: '#1E4A8C',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 10,
    paddingBottom: 20,
    paddingHorizontal: 10,
    alignItems: 'center',
    height: 230,
    justifyContent: 'flex-start',
    shadowColor: '#1E4A8C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 2,
    marginHorizontal: 4,
  },
  sideCard: {
    width: width * 0.27,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 14,
    paddingBottom: 16,
    paddingHorizontal: 8,
    alignItems: 'center',
    height: 175,
    justifyContent: 'flex-start',
    shadowColor: '#A0B4D6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 1,
  },
  rankBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  rankBadgeText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: '900',
  },
  podiumName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#2A4A70',
    marginTop: 12,
    textAlign: 'center',
  },
  podiumScore: {
    fontSize: 17,
    fontWeight: '900',
    color: '#4A90D9',
    marginTop: 2,
  },
  podiumLabel: {
    fontSize: 11,
    color: '#7A90B0',
    fontWeight: '600',
    marginTop: 1,
  },

  // Stats
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 16,
    alignItems: 'flex-start',
    shadowColor: '#A0B4D6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
  },
  statIconBg: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statLabel: {
    fontSize: 11,
    color: '#8899BB',
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  statValue: {
    fontSize: 26,
    fontWeight: '900',
    marginTop: 2,
    letterSpacing: -0.5,
  },

  // Rising Stars
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A3558',
  },
  rankBadgeWrap: {
    backgroundColor: '#E8F0FC',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  rankBadgeLabel: {
    fontSize: 12,
    color: '#4A90D9',
    fontWeight: '700',
  },
  starsList: {
    gap: 10,
  },
  starRow: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#A0B4D6',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
    gap: 12,
  },
  starRankWrap: {
    width: 28,
    alignItems: 'center',
  },
  starRankNum: {
    fontSize: 16,
    fontWeight: '900',
    color: '#A0B4C8',
  },
  starInfo: {
    flex: 1,
  },
  starName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A3558',
  },
  starLevel: {
    fontSize: 12,
    color: '#7A90B0',
    fontWeight: '500',
    marginTop: 1,
  },
  starAccuracy: {
    fontSize: 17,
    fontWeight: '900',
  },
  starAccLabel: {
    fontSize: 10,
    color: '#A0B0C0',
    fontWeight: '600',
    marginTop: 1,
  },
});
